
#wideform
set.seed(1)
m <- matrix(sample(15, 15), 5, 3)
rownames(m) <- paste0("Row", 1:5)
colnames(m) <- paste0("Col", 1:3)

#lognform
# Or use a data frame
df <- data.frame(from = rep(rownames(m), ncol(m)),
                 to = rep(colnames(m), each = nrow(m)),
                 value = as.vector(m))


#install.packages("circlize")
library(circlize)

chordDiagram(m) #wideform에 바로 적용

# Restart circular layout parameters
circos.clear()


#여러변수간의 상관관계 시각화

m1 <- as.matrix(cor(iris[,1:4]))
chordDiagram(m1) #wideform에 바로 적용
circos.clear()



cols <- hcl.colors(16, "Temps")

chordDiagram(m1,
             col = cols,
             transparency = 0.1,
             link.lwd = 1,    # Line width
             link.lty = 1,    # Line type
             link.border = 1) # Border color

circos.clear()


m1
cols <- hcl.colors(16, "Geyser")
mb <- matrix("black", nrow = 1, ncol = ncol(m1))
rownames(mb) <- rownames(m1)[2] # Third row
colnames(mb) <- colnames(m1)

chordDiagram(m1,
             col = cols,
             transparency = 0.1,
             link.lwd = 2,     # Line width
             link.lty = 2,     # Line type
             link.border = mb) # Border color

circos.clear()



chordDiagram(m, column.col = c("red", "green", "blue"),
             annotationTrack = "grid",
             annotationTrackHeight = c(0.04, 0.02))


chordDiagram(m, column.col = c("red", "green", "blue"),
             annotationTrack =  c("name", "grid"))

circos.clear()
